### ISSUE TITLE
Deploying to Tableau Server

### ISSUE THREAD

**Issue by myox** [demartsc/tableau-react-annotation#7]
Hi Chris, 

This is excellent - thanks for making all your code open-source. I've enjoyed working through it,

I'm in the process of building my own extension (although I'm very much a JS beginner) and I'm trying to find a way to make the extension transparent (i.e. click-through). My problem is CORS and I thought you may have solved it, but the click-through functionality doesn't work for me when I've publish the extension (CORS error in console) and I assume it's because I've not deployed the extension itself to Tableau server. How do you do this? I have server admin permissions but only have access to the online server admin UI. 

Are you aware of any other ways of getting around this? I'd really like my extension to load as a modal to the parent (viz) window, but I'm struggling! I guess I may have to resort to a pop-up window instead.

Cheers,

Mark

**Comment by demartsc** [comment]
@myox - my apologies, I am just now realizing that I never responded to this question! I realize it is likely to late to be of help and am sorry about that. I appreciate the nice words re the code and open sourcing of it. 

With regards to your question, you are correct that any time you try to climb the DOM out of the iFrame (in either extensions or JavaScript (embedding) APIs you will run into this CORS issue. The way we have historically gotten around this is by deploying the code directly onto the Tableau Server itself. This is not ideal, obviously, but the more we ask/push Tableau for these types of functionalities the better :) 

Here are two old articles that walks through our approach of hosting on Tableau Server itself: 

- https://databoss.starschema.net/tableau-javascript-api-without-embedding/ by Tamas Foldi
- https://www.datablick.com/blog/category/D3 has a few different blogs where I leverage this technique at varying levels of capabilities depending on where the Tableau product was at during that time period. 

Sorry again about the delay in response. 
Chris
